// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIY3TUh1CMt72v-LbLYY7RACHISkY_MlA',
    appId: '1:572219831254:web:eb578252ef66715545ea77',
    messagingSenderId: '572219831254',
    projectId: 'sarie-46b77',
    authDomain: 'sarie-46b77.firebaseapp.com',
    storageBucket: 'sarie-46b77.appspot.com',
    measurementId: 'G-P1NT967B7W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqcHoZA2x3CFq-TXi-H13X34iFJsLWx1I',
    appId: '1:572219831254:android:f495b55af7a1509945ea77',
    messagingSenderId: '572219831254',
    projectId: 'sarie-46b77',
    storageBucket: 'sarie-46b77.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHEU51w-VPsDYkmBilpTzDSYNjqaBiHyw',
    appId: '1:572219831254:ios:df3992a4b37034d745ea77',
    messagingSenderId: '572219831254',
    projectId: 'sarie-46b77',
    storageBucket: 'sarie-46b77.appspot.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHEU51w-VPsDYkmBilpTzDSYNjqaBiHyw',
    appId: '1:572219831254:ios:df3992a4b37034d745ea77',
    messagingSenderId: '572219831254',
    projectId: 'sarie-46b77',
    storageBucket: 'sarie-46b77.appspot.com',
    iosBundleId: 'com.example.userApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIY3TUh1CMt72v-LbLYY7RACHISkY_MlA',
    appId: '1:572219831254:web:e4939a1af969eb3645ea77',
    messagingSenderId: '572219831254',
    projectId: 'sarie-46b77',
    authDomain: 'sarie-46b77.firebaseapp.com',
    storageBucket: 'sarie-46b77.appspot.com',
    measurementId: 'G-1K4YB77DEW',
  );
}
